name: Changesets
on:
  push:
    branches:
      - master
env:
  CI: true
  PNPM_CACHE_FOLDER: .pnpm-store
permissions: write-all
jobs:
  version:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          registry-url: 'https://registry.npmjs.org'

      - name: Install pnpm
        run: npm i pnpm@latest -g

      - name: Setup pnpm config
        run: pnpm config set store-dir $PNPM_CACHE_FOLDER

      - name: Install dependencies
        run: pnpm install

      - name: Prep commit message
        run: |
          echo "NEW_VERSION=$(pnpm changeset status --output=release.json && jq -r '.releases[0].newVersion' release.json && rm release.json)" >> "$GITHUB_ENV"

      - name: Create and publish versions
        uses: changesets/action@v1
        id: changesets
        with:
          version: pnpm changeset version
          title: "CI: Release v${{env.NEW_VERSION}}"
          commit: "CI: Release v${{env.NEW_VERSION}}"
          publish: pnpm run ci:publish
        env:
          GITHUB_TOKEN: ${{ secrets.CHANGESETS_PR_PAT }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Create job summary from published packages
        if: steps.changesets.outputs.published == 'true'
        run: |
          echo "## Published Packages :package:" >> $GITHUB_STEP_SUMMARY          
          
          # Check if the publishedPackages array is empty
          PACKAGES_COUNT=$(jq '.publishedPackages | length' pnpm-publish-summary.json)
          if [ "$PACKAGES_COUNT" -eq 0 ]; then
            echo "No packages were published." >> $GITHUB_STEP_SUMMARY
          else
            # If packages were published, format and list them
            jq -r '.publishedPackages[] | "- [\(.name)@\(.version)](https://www.npmjs.com/package/\(.name)/v/\(.version))"' pnpm-publish-summary.json >> $GITHUB_STEP_SUMMARY
          fi    
