name: Changesets
on:
  push:
    branches:
      - master
env:
  CI: true
  PNPM_CACHE_FOLDER: .pnpm-store
permissions: write-all
jobs:
  version:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          registry-url: 'https://registry.npmjs.org'

      - name: Install pnpm
        run: npm i pnpm@latest -g

      - name: Setup pnpm config
        run: pnpm config set store-dir $PNPM_CACHE_FOLDER

      - name: Install dependencies
        run: pnpm install

      - name: Create and publish versions
        uses: changesets/action@v1
        with:
          version: pnpm changeset version
          commit: "CI: Update versions"
          title: "CI: Update versions"
          publish: pnpm run ci:publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Create job summary from published packages
        run: |
          echo "## Published Packages" >> $GITHUB_STEP_SUMMARY          
          
          # Read the JSON file and format its contents
          jq -r '.publishedPackages[] | "- \(.name) version \(.version)"' pnpm-publish-summary.json >> $GITHUB_STEP_SUMMARY        
