name: CI
on:
  push:
    branches: [master]
  pull_request:
permissions:
  contents: read # to fetch code (actions/checkout)

env:
  PNPM_CACHE_FOLDER: .pnpm-store
#  # We only install Chromium manually
#  PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: '1'

jobs:
  Tests:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 15
    strategy:
      matrix:
        include:
#          - node-version: 18
#            os: windows-latest
#          - node-version: 18
#            os: macOS-latest
#          - node-version: 18
#            os: ubuntu-latest
          - node-version: 20
            os: ubuntu-latest
#          - node-version: 21
#            os: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: setup node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          registry-url: 'https://registry.npmjs.org'
      - name: install pnpm
        run: npm i pnpm@latest -g
      - name: setup pnpm config
        run: pnpm config set store-dir $PNPM_CACHE_FOLDER
      - run: pnpm install --frozen-lockfile
      - run: pnpm test
        env:
          CI: true
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
