name: Prerelease

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  prerelease:
    if: github.head_ref == 'changeset-release/master'
    outputs:
      coreVersion: ${{ steps.version.outputs.coreVersion }}
    runs-on: ubuntu-latest
    steps:

      - name: checkout code repository
        uses: actions/checkout@v3

      - name: setup node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          registry-url: 'https://registry.npmjs.org'

      - name: install pnpm
        run: npm i pnpm@latest -g

      - name: setup pnpm config
        run: pnpm config set store-dir $PNPM_CACHE_FOLDER

      - name: install dependencies
        run: pnpm install

      - name: Add prerelease tag with git SHA to public packages
        id: version
        run: |
          # Get the current git SHA
          git_sha=$(git rev-parse --short HEAD)        

          # Get the list of packages in the workspace
          packages=$(pnpm m ls --json --depth=-1)          

          # Iterate over each package
          for package in $(echo "$packages" | jq -c '.[]'); do
            private=$(echo "$package" | jq -r '.private')
            version=$(echo "$package" | jq -r '.version')
            name=$(echo "$package" | jq -r '.name')
            path=$(echo "$package" | jq -r '.path')

            # Check if the package is public and has a version
            if [ "$private" = "false" ] && [ "$version" != "null" ]; then
              # Add prerelease tag with git SHA to the version
              new_version="${version}-rc.${git_sha}"

              # Update the package version in package.json using jq
              jq --arg version "$new_version" '.version = $version' "$path/package.json" > tmp.json && mv tmp.json "$path/package.json"
              cat "$path/package.json"
          
              if [ "$name" = "@performer/core" ]; then
                echo "coreVersion=$version" >> $GITHUB_OUTPUT
              fi
            fi
          done

      - name: Publish Prerelease
        run: |
          git_sha=$(git rev-parse --short HEAD)
          pnpm publish -r --report-summary --no-git-checks --access public --tag "rc.$git_sha"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Create job summary from published packages
        run: |
          echo "## Published Packages :package:" >> $GITHUB_STEP_SUMMARY
          echo "Snapshot Name: **${{ github.event.pull_request.head.ref }}**" >> $GITHUB_STEP_SUMMARY

          PACKAGES_COUNT=$(jq '.publishedPackages | length' pnpm-publish-summary.json)
          if [ "$PACKAGES_COUNT" -eq 0 ]; then
            echo "No packages were published." >> $GITHUB_STEP_SUMMARY
          else
            jq -r '.publishedPackages[] | "- [\(.name)@\(.version)](https://www.npmjs.com/package/\(.name)/v/\(.version))"' pnpm-publish-summary.json >> $GITHUB_STEP_SUMMARY
          fi

  test-create-performer:
    needs: prerelease
    runs-on: ${{ matrix.os }}
    timeout-minutes: 15
    strategy:
      matrix:
        include:
          - node-version: 20
            os: ubuntu-latest
          - node-version: 20
            os: windows-latest
          - node-version: 20
            os: macOS-latest
      fail-fast: false
    steps:

      - name: setup node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: 'https://registry.npmjs.org'

      - name: install pnpm
        run: npm i pnpm@latest -g

      - name: setup pnpm config
        run: pnpm config set store-dir $PNPM_CACHE_FOLDER

      - name: Extract commit SHA
        id: extract_sha
        shell: bash
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Create project
        if: runner.os != 'Windows'
        run: |
          git_sha=$(echo $GITHUB_SHA | cut -c1-7)          
          pnpm create "performer@rc.$git_sha" my-project

      - name: Create project (Windows)
        if: runner.os == 'Windows'
        run: |
          $git_sha = $env:GITHUB_SHA.Substring(0, 7)
          npm create "performer@rc.$($git_sha)" my-project      

      - name: Update performer dependency to prerelease
        if: runner.os != 'Windows'
        run: |
          git_sha=$(echo $GITHUB_SHA | cut -c1-7)   
          echo coreVersion ${{ needs.prerelease.outputs.coreVersion }}
          pkgVersion="${{ needs.prerelease.outputs.coreVersion }}@rc.$git_sha"
          echo pkgVersion $pkgVersion
          sed -i "s|\"@performer/core\": \"latest\"|\"@performer/core\": \"$pkgVersion\"|" package.json
          cat package.json
        working-directory: ./my-project

      - name: Install performer app dependencies
        run: pnpm install
        working-directory: ./my-project

      - name: Run tests
        run: pnpm test
        working-directory: ./my-project
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          LOGLEVEL: silent

